url: "https://hansschnedlitz.com"
baseurl: "/rubyevents-guides"
title: "Ruby Community Guides"
description: "Practical guides for starting and running Ruby communities."

exclude:
  - vendor
  - .bundle
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - interviews
